### PR TITLE
update to 1.2.6

### PR DESCRIPTION
**Pull request by ocefpaf**
Fix https://github.com/pyoceans/pocean-core/issues/30

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please add noarch: python

**Comment by kwilcox** [comment]
@ocefpaf this broke pocean, it is no longer importable.

**Comment by kwilcox** [comment]
I don't really know how `noarch` packages should work but there is no directory in `site-packages` for `pocean` when installing through `conda-forge`. I can install from `axiom-data-science` and it works fine.

**Comment by ocefpaf** [comment]
I'll revert the change and check why this didn't work for pocean later
today. (Away from the laptop at the moment.)

**Pull request merged**
